name: Update Metadata

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  push:
  workflow_dispatch:



jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.README }}


    - name: Fetch metadata count
      id: fetch-metadata
      run: |
        API_RESPONSE=$(curl -s 'https://api.zed.dev/extensions?filter=The%20Dark%20Side')
        DOWNLOAD_COUNT=$(echo "$API_RESPONSE" | jq -r '.data[0].download_count')
        VERSION=$(echo "$API_RESPONSE" | jq -r '.data[0].version')
        echo "::set-output name=download_count::$DOWNLOAD_COUNT"
        echo "::set-output name=version::$VERSION"
        

    - name: Update README.md with download count
      run: |
        DOWNLOAD_COUNT=${{ steps.fetch-metadata.outputs.download_count }}
        VERSION=${{ steps.fetch-metadata.outputs.version }}
        VERSION_URL="https://img.shields.io/badge/version-$VERSION-8A2BE2?style=for-the-badge&label=Version&labelColor=363a4f&color=9a77cf"
        BADGE_URL="https://img.shields.io/badge/downloads-$DOWNLOAD_COUNT-df881d?style=for-the-badge&label=Downloads&labelColor=363a4f&color=df881d"
        BADGES_HTML="<div align=\"center\">\n\n<table style=\"border: none;\"><tr style=\"border: none;\">\n<td style=\"border: none;\"><img src=\"https://img.shields.io/badge/Zed-8A2BE2?style=for-the-badge&label=Build%20For&color=e5c07b&labelColor=363a4f\" alt=\"Static Badge\"></td>\n\n<!-- DOWNLOADS_BADGE_START -->\n<td style=\"border: none;\"><img src=\"$BADGE_URL\" alt=\"Downloads Badge\"></td>\n<!-- DOWNLOADS_BADGE_END -->\n\n<!-- VERSION_BADGE_START -->\n<td style=\"border: none;\"><img src=\"$VERSION_URL\" alt=\"Version Badge\"></td>\n<!-- VERSION_BADGE_END -->\n</tr></table>\n\n</div>"
        sed -i "/<!-- BADGES_PLACEHOLDER_START -->/,/<!-- BADGES_PLACEHOLDER_END -->/c\$BADGES_HTML" README.md


    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update download count badge" -a || echo "No changes to commit"
        git push
